#!/usr/bin/env python3
"""
Automate short-vs-long context serving benchmarks and export comparison files.

Mode 1: run benchmark matrix (`--mode run`, default)
- Concurrency: 1, 10, 20
- Short context: input=1024, output=100, num_prompts=concurrency*10
- Long context: input=30000, output=1000, num_prompts=concurrency*10

Output files:
1) raw JSONL for each run
2) runs_summary.csv
3) short_vs_long_comparison.csv
4) short_vs_long_summary.md

Mode 2: compare A/B runs (`--mode compare-ab`)
- Compare baseline directory vs optimized directory (for example CSAttention on/off)
- Both directories should contain runs_summary.csv generated by this script

Output files:
1) ab_comparison.csv
2) ab_summary.md
"""

from __future__ import annotations

import argparse
import csv
import json
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


@dataclass(frozen=True)
class BenchCase:
    context_group: str  # "short" or "long"
    concurrency: int
    input_len: int
    output_len: int
    num_prompts: int


THROUGHPUT_METRICS = [
    "request_throughput",
    "output_throughput",
    "total_throughput",
]

LATENCY_METRICS = [
    "mean_e2e_latency_ms",
    "p99_e2e_latency_ms",
    "mean_ttft_ms",
    "p99_ttft_ms",
    "mean_itl_ms",
    "p99_itl_ms",
]

METRICS_FOR_SUMMARY = THROUGHPUT_METRICS + LATENCY_METRICS


def parse_int_list(value: str) -> List[int]:
    items = [x.strip() for x in value.split(",") if x.strip()]
    if not items:
        raise argparse.ArgumentTypeError("Empty list is not allowed.")
    try:
        ints = [int(x) for x in items]
    except ValueError as exc:
        raise argparse.ArgumentTypeError(
            f"Invalid integer list: {value}"
        ) from exc
    if any(v <= 0 for v in ints):
        raise argparse.ArgumentTypeError("All values must be > 0.")
    return ints


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run automated short/long context benchmarks, or compare two runs "
            "(baseline vs optimized)."
        )
    )

    parser.add_argument(
        "--mode",
        choices=["run", "compare-ab"],
        default="run",
        help="run: execute benchmark matrix; compare-ab: compare two run directories.",
    )

    # Run mode args.
    parser.add_argument(
        "--backend",
        type=str,
        default="sglang",
        help="Backend passed to sglang.bench_serving (run mode).",
    )
    parser.add_argument(
        "--base-url",
        type=str,
        default=None,
        help="If set, pass --base-url to bench_serving (run mode).",
    )
    parser.add_argument(
        "--host",
        type=str,
        default="127.0.0.1",
        help="Server host when --base-url is not used (run mode).",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=30000,
        help="Server port when --base-url is not used (run mode).",
    )
    parser.add_argument(
        "--model",
        type=str,
        default=None,
        help="Model id/path passed to bench_serving (run mode).",
    )
    parser.add_argument(
        "--tokenizer",
        type=str,
        default=None,
        help="Optional tokenizer id/path passed to bench_serving (run mode).",
    )
    parser.add_argument(
        "--concurrencies",
        type=parse_int_list,
        default=parse_int_list("1,10,20"),
        help="Comma-separated concurrency values (run mode).",
    )
    parser.add_argument(
        "--request-multiplier",
        type=int,
        default=10,
        help="num_prompts = concurrency * request_multiplier (run mode).",
    )
    parser.add_argument(
        "--short-input-len",
        type=int,
        default=1024,
        help="Short context input length (run mode).",
    )
    parser.add_argument(
        "--short-output-len",
        type=int,
        default=100,
        help="Short context output length (run mode).",
    )
    parser.add_argument(
        "--long-input-len",
        type=int,
        default=30000,
        help="Long context input length (run mode).",
    )
    parser.add_argument(
        "--long-output-len",
        type=int,
        default=1000,
        help="Long context output length (run mode).",
    )
    parser.add_argument(
        "--request-rate",
        type=str,
        default="inf",
        help="Request rate for bench_serving (run mode).",
    )
    parser.add_argument(
        "--random-range-ratio",
        type=float,
        default=0.0,
        help="Random length range ratio for random dataset (run mode).",
    )
    parser.add_argument(
        "--warmup-requests",
        type=int,
        default=1,
        help="Warmup requests per run (run mode).",
    )
    parser.add_argument(
        "--extra-request-body",
        type=str,
        default=None,
        help='Optional JSON string forwarded to --extra-request-body (run mode).',
    )
    parser.add_argument(
        "--apply-chat-template",
        action="store_true",
        help="Pass --apply-chat-template to bench_serving (run mode).",
    )
    parser.add_argument(
        "--disable-stream",
        action="store_true",
        help="Pass --disable-stream to bench_serving (run mode).",
    )
    parser.add_argument(
        "--flush-cache",
        action="store_true",
        help="Pass --flush-cache to bench_serving before each run (run mode).",
    )
    parser.add_argument(
        "--tag-prefix",
        type=str,
        default="context_cmp",
        help="Tag prefix written into bench_serving result (run mode).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output directory (run mode). Default: benchmark/context_compare/<timestamp>.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print commands only, do not execute benchmark (run mode).",
    )
    parser.add_argument(
        "--live-log",
        action="store_true",
        help=(
            "Stream bench_serving stdout/stderr to terminal while still writing "
            "full logs to files (run mode)."
        ),
    )
    parser.add_argument(
        "--output-details",
        action="store_true",
        help=(
            "Forward --output-details to bench_serving so per-request arrays "
            "(ttfts/itls/errors) are included in raw JSONL outputs (run mode)."
        ),
    )

    # A/B compare mode args.
    parser.add_argument(
        "--baseline-dir",
        type=Path,
        default=None,
        help="Baseline run directory containing runs_summary.csv (compare-ab mode).",
    )
    parser.add_argument(
        "--optimized-dir",
        type=Path,
        default=None,
        help="Optimized run directory containing runs_summary.csv (compare-ab mode).",
    )
    parser.add_argument(
        "--optimized-label",
        type=str,
        default="csattention",
        help="Label for optimized run in A/B report (compare-ab mode).",
    )
    parser.add_argument(
        "--ab-output-dir",
        type=Path,
        default=None,
        help=(
            "A/B report output directory (compare-ab mode). "
            "Default: <optimized-dir>/ab_compare_vs_<baseline-dir-name>."
        ),
    )

    return parser.parse_args()


def ensure_extra_request_body_is_json(extra_request_body: Optional[str]) -> None:
    if extra_request_body is None:
        return
    try:
        parsed = json.loads(extra_request_body)
    except json.JSONDecodeError as exc:
        raise ValueError(f"--extra-request-body is not valid JSON: {exc}") from exc
    if not isinstance(parsed, dict):
        raise ValueError("--extra-request-body must be a JSON object.")


def build_cases(args: argparse.Namespace) -> List[BenchCase]:
    cases: List[BenchCase] = []
    for concurrency in args.concurrencies:
        num_prompts = concurrency * args.request_multiplier
        cases.append(
            BenchCase(
                context_group="short",
                concurrency=concurrency,
                input_len=args.short_input_len,
                output_len=args.short_output_len,
                num_prompts=num_prompts,
            )
        )
        cases.append(
            BenchCase(
                context_group="long",
                concurrency=concurrency,
                input_len=args.long_input_len,
                output_len=args.long_output_len,
                num_prompts=num_prompts,
            )
        )
    return cases


def build_output_dir(base_output_dir: Optional[Path]) -> Path:
    if base_output_dir is not None:
        out_dir = base_output_dir
    else:
        now = datetime.now().strftime("%Y%m%d_%H%M%S")
        out_dir = Path("benchmark") / "context_compare" / now
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "raw").mkdir(parents=True, exist_ok=True)
    (out_dir / "logs").mkdir(parents=True, exist_ok=True)
    return out_dir


def build_bench_cmd(
    args: argparse.Namespace,
    case: BenchCase,
    output_file: Path,
) -> List[str]:
    cmd = [
        sys.executable,
        "-m",
        "sglang.bench_serving",
        "--backend",
        args.backend,
        "--dataset-name",
        "random",
        "--num-prompts",
        str(case.num_prompts),
        "--random-input-len",
        str(case.input_len),
        "--random-output-len",
        str(case.output_len),
        "--random-range-ratio",
        str(args.random_range_ratio),
        "--request-rate",
        str(args.request_rate),
        "--max-concurrency",
        str(case.concurrency),
        "--warmup-requests",
        str(args.warmup_requests),
        "--output-file",
        str(output_file),
        "--tag",
        f"{args.tag_prefix}_{case.context_group}_c{case.concurrency}",
    ]

    if args.base_url:
        cmd.extend(["--base-url", args.base_url])
    else:
        cmd.extend(["--host", args.host, "--port", str(args.port)])

    if args.model:
        cmd.extend(["--model", args.model])
    if args.tokenizer:
        cmd.extend(["--tokenizer", args.tokenizer])
    if args.extra_request_body:
        cmd.extend(["--extra-request-body", args.extra_request_body])
    if args.apply_chat_template:
        cmd.append("--apply-chat-template")
    if args.disable_stream:
        cmd.append("--disable-stream")
    if args.flush_cache:
        cmd.append("--flush-cache")
    if args.output_details:
        cmd.append("--output-details")

    return cmd


def run_command(cmd: List[str], log_file: Path, dry_run: bool, live_log: bool) -> None:
    command_str = " ".join(cmd)
    print(f"[RUN] {command_str}")
    if dry_run:
        return

    with log_file.open("w", encoding="utf-8") as f:
        f.write(f"COMMAND:\n{command_str}\n\nOUTPUT:\n")
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        assert process.stdout is not None
        for line in process.stdout:
            f.write(line)
            if live_log:
                print(line, end="")
        returncode = process.wait()

    if returncode != 0:
        raise RuntimeError(
            f"Command failed with exit code {returncode}. See log: {log_file}"
        )


def load_last_jsonl_record(path: Path) -> Dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Output file not found: {path}")
    lines = [line.strip() for line in path.read_text(encoding="utf-8").splitlines()]
    lines = [line for line in lines if line]
    if not lines:
        raise ValueError(f"No JSONL records found in {path}")
    return json.loads(lines[-1])


def to_float(value: Any) -> Optional[float]:
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        s = value.strip()
        if not s:
            return None
        try:
            return float(s)
        except ValueError:
            return None
    return None


def to_int(value: Any) -> Optional[int]:
    if isinstance(value, int):
        return value
    fval = to_float(value)
    if fval is None:
        return None
    return int(round(fval))


def format_num(value: Any, precision: int = 4) -> str:
    fval = to_float(value)
    if fval is None:
        return ""
    return f"{fval:.{precision}f}"


def collect_run_row(case: BenchCase, result: Dict[str, Any], raw_file: Path) -> Dict[str, Any]:
    row: Dict[str, Any] = {
        "context_group": case.context_group,
        "concurrency": case.concurrency,
        "input_len": case.input_len,
        "output_len": case.output_len,
        "num_prompts": case.num_prompts,
        "raw_result_file": str(raw_file),
    }
    row.update(result)
    return row


def write_csv(path: Path, rows: Iterable[Dict[str, Any]]) -> None:
    row_list = list(rows)
    if not row_list:
        path.write_text("", encoding="utf-8")
        return

    fieldnames: List[str] = []
    fieldname_set = set()
    for row in row_list:
        for key in row.keys():
            if key not in fieldname_set:
                fieldname_set.add(key)
                fieldnames.append(key)

    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in row_list:
            writer.writerow(row)


def read_csv(path: Path) -> List[Dict[str, Any]]:
    if not path.exists():
        raise FileNotFoundError(f"Missing CSV file: {path}")
    with path.open("r", newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        rows: List[Dict[str, Any]] = []
        for row in reader:
            cleaned = {
                str(k).replace("\ufeff", "").strip(): v
                for k, v in dict(row).items()
                if k is not None
            }
            rows.append(cleaned)
        return rows


def build_short_long_comparison_rows(run_rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    by_key: Dict[Tuple[int, str], Dict[str, Any]] = {}
    for row in run_rows:
        concurrency = to_int(row.get("concurrency"))
        context_group = str(row.get("context_group", ""))
        if concurrency is None or not context_group:
            continue
        key = (concurrency, context_group)
        by_key[key] = row

    all_concurrency = sorted(
        {to_int(row.get("concurrency")) for row in run_rows if to_int(row.get("concurrency")) is not None}
    )
    comparison_rows: List[Dict[str, Any]] = []

    for concurrency in all_concurrency:
        short_row = by_key.get((concurrency, "short"))
        long_row = by_key.get((concurrency, "long"))
        if not short_row or not long_row:
            continue

        row: Dict[str, Any] = {
            "concurrency": concurrency,
            "short_input_len": to_int(short_row.get("input_len")),
            "short_output_len": to_int(short_row.get("output_len")),
            "short_num_prompts": to_int(short_row.get("num_prompts")),
            "long_input_len": to_int(long_row.get("input_len")),
            "long_output_len": to_int(long_row.get("output_len")),
            "long_num_prompts": to_int(long_row.get("num_prompts")),
        }

        for metric in METRICS_FOR_SUMMARY:
            short_value = to_float(short_row.get(metric))
            long_value = to_float(long_row.get(metric))
            row[f"short_{metric}"] = short_value
            row[f"long_{metric}"] = long_value
            if short_value is None or long_value is None:
                row[f"long_minus_short_{metric}"] = None
                row[f"long_div_short_{metric}"] = None
                continue
            row[f"long_minus_short_{metric}"] = long_value - short_value
            row[f"long_div_short_{metric}"] = (
                (long_value / short_value) if short_value != 0 else None
            )

        comparison_rows.append(row)
    return comparison_rows


def write_short_long_markdown_summary(path: Path, comparison_rows: List[Dict[str, Any]]) -> None:
    lines: List[str] = []
    lines.append("# Short vs Long Context Benchmark Summary")
    lines.append("")
    lines.append(
        "| concurrency | req/s short | req/s long | long/short req/s | "
        "mean TTFT short(ms) | mean TTFT long(ms) | long/short TTFT | "
        "mean ITL short(ms) | mean ITL long(ms) | long/short ITL |"
    )
    lines.append("|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for row in comparison_rows:
        lines.append(
            "| "
            + f"{row['concurrency']} | "
            + f"{format_num(row.get('short_request_throughput'), 2)} | "
            + f"{format_num(row.get('long_request_throughput'), 2)} | "
            + f"{format_num(row.get('long_div_short_request_throughput'), 3)} | "
            + f"{format_num(row.get('short_mean_ttft_ms'), 2)} | "
            + f"{format_num(row.get('long_mean_ttft_ms'), 2)} | "
            + f"{format_num(row.get('long_div_short_mean_ttft_ms'), 3)} | "
            + f"{format_num(row.get('short_mean_itl_ms'), 2)} | "
            + f"{format_num(row.get('long_mean_itl_ms'), 2)} | "
            + f"{format_num(row.get('long_div_short_mean_itl_ms'), 3)} |"
        )
    lines.append("")
    lines.append("Long/short ratio interpretation:")
    lines.append("- Throughput metrics: higher is better.")
    lines.append("- Latency metrics: lower is better.")
    path.write_text("\n".join(lines), encoding="utf-8")


def build_case_key(row: Dict[str, Any]) -> Optional[Tuple[str, int, int, int, int]]:
    context_group = str(row.get("context_group", "")).strip()
    concurrency = to_int(row.get("concurrency"))
    input_len = to_int(row.get("input_len"))
    output_len = to_int(row.get("output_len"))
    num_prompts = to_int(row.get("num_prompts"))
    if (
        not context_group
        or concurrency is None
        or input_len is None
        or output_len is None
        or num_prompts is None
    ):
        return None
    return (context_group, concurrency, input_len, output_len, num_prompts)


def index_by_case(rows: List[Dict[str, Any]]) -> Dict[Tuple[str, int, int, int, int], Dict[str, Any]]:
    indexed: Dict[Tuple[str, int, int, int, int], Dict[str, Any]] = {}
    for row in rows:
        key = build_case_key(row)
        if key is None:
            continue
        indexed[key] = row
    return indexed


def safe_ratio(num: Optional[float], den: Optional[float]) -> Optional[float]:
    if num is None or den is None or den == 0:
        return None
    return num / den


def oriented_gain_pct(metric: str, baseline: Optional[float], optimized: Optional[float]) -> Optional[float]:
    if baseline is None or optimized is None or baseline == 0:
        return None
    if metric in THROUGHPUT_METRICS:
        return (optimized - baseline) / baseline * 100.0
    return (baseline - optimized) / baseline * 100.0


def mean_non_none(values: Iterable[Optional[float]]) -> Optional[float]:
    keep = [v for v in values if v is not None]
    if not keep:
        return None
    return sum(keep) / len(keep)


def build_ab_rows(
    baseline_rows: List[Dict[str, Any]],
    optimized_rows: List[Dict[str, Any]],
    optimized_label: str,
) -> List[Dict[str, Any]]:
    baseline_index = index_by_case(baseline_rows)
    optimized_index = index_by_case(optimized_rows)

    common_keys = sorted(set(baseline_index.keys()) & set(optimized_index.keys()))
    ab_rows: List[Dict[str, Any]] = []

    for key in common_keys:
        context_group, concurrency, input_len, output_len, num_prompts = key
        baseline_row = baseline_index[key]
        optimized_row = optimized_index[key]

        row: Dict[str, Any] = {
            "context_group": context_group,
            "concurrency": concurrency,
            "input_len": input_len,
            "output_len": output_len,
            "num_prompts": num_prompts,
            "baseline_raw_result_file": baseline_row.get("raw_result_file"),
            f"{optimized_label}_raw_result_file": optimized_row.get("raw_result_file"),
        }

        for metric in METRICS_FOR_SUMMARY:
            b = to_float(baseline_row.get(metric))
            o = to_float(optimized_row.get(metric))
            row[f"baseline_{metric}"] = b
            row[f"{optimized_label}_{metric}"] = o
            row[f"{optimized_label}_minus_baseline_{metric}"] = (
                (o - b) if b is not None and o is not None else None
            )
            row[f"{optimized_label}_div_baseline_{metric}"] = safe_ratio(o, b)
            row[f"gain_pct_{metric}"] = oriented_gain_pct(metric, b, o)

        ab_rows.append(row)

    return ab_rows


def write_ab_summary_markdown(path: Path, ab_rows: List[Dict[str, Any]], optimized_label: str) -> None:
    lines: List[str] = []
    lines.append(f"# Baseline vs {optimized_label} Summary")
    lines.append("")
    lines.append(
        "| context | concurrency | req/s baseline | req/s "
        + optimized_label
        + " | req/s gain% | TTFT baseline(ms) | TTFT "
        + optimized_label
        + "(ms) | TTFT gain% | ITL baseline(ms) | ITL "
        + optimized_label
        + "(ms) | ITL gain% |"
    )
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for row in ab_rows:
        lines.append(
            "| "
            + f"{row['context_group']} | "
            + f"{row['concurrency']} | "
            + f"{format_num(row.get('baseline_request_throughput'), 2)} | "
            + f"{format_num(row.get(f'{optimized_label}_request_throughput'), 2)} | "
            + f"{format_num(row.get('gain_pct_request_throughput'), 2)} | "
            + f"{format_num(row.get('baseline_mean_ttft_ms'), 2)} | "
            + f"{format_num(row.get(f'{optimized_label}_mean_ttft_ms'), 2)} | "
            + f"{format_num(row.get('gain_pct_mean_ttft_ms'), 2)} | "
            + f"{format_num(row.get('baseline_mean_itl_ms'), 2)} | "
            + f"{format_num(row.get(f'{optimized_label}_mean_itl_ms'), 2)} | "
            + f"{format_num(row.get('gain_pct_mean_itl_ms'), 2)} |"
        )

    lines.append("")
    lines.append("Average gain across matched cases (positive is better):")
    lines.append(
        "- request_throughput: "
        + format_num(mean_non_none([to_float(r.get("gain_pct_request_throughput")) for r in ab_rows]), 2)
        + "%"
    )
    lines.append(
        "- mean_ttft_ms: "
        + format_num(mean_non_none([to_float(r.get("gain_pct_mean_ttft_ms")) for r in ab_rows]), 2)
        + "%"
    )
    lines.append(
        "- mean_itl_ms: "
        + format_num(mean_non_none([to_float(r.get("gain_pct_mean_itl_ms")) for r in ab_rows]), 2)
        + "%"
    )
    lines.append("")
    lines.append("Gain definition:")
    lines.append("- Throughput gain% = (optimized - baseline) / baseline * 100")
    lines.append("- Latency gain% = (baseline - optimized) / baseline * 100")
    path.write_text("\n".join(lines), encoding="utf-8")


def run_mode(args: argparse.Namespace) -> None:
    ensure_extra_request_body_is_json(args.extra_request_body)

    if args.request_multiplier <= 0:
        raise ValueError("--request-multiplier must be > 0.")

    output_dir = build_output_dir(args.output_dir)
    print(f"Output directory: {output_dir.resolve()}")

    cases = build_cases(args)
    run_rows: List[Dict[str, Any]] = []

    for case in cases:
        case_name = (
            f"{case.context_group}_c{case.concurrency}_in{case.input_len}_out{case.output_len}"
        )
        raw_file = output_dir / "raw" / f"{case_name}.jsonl"
        log_file = output_dir / "logs" / f"{case_name}.log"
        cmd = build_bench_cmd(args, case, raw_file)
        run_command(cmd, log_file, args.dry_run, args.live_log)
        if args.dry_run:
            continue
        result = load_last_jsonl_record(raw_file)
        run_rows.append(collect_run_row(case, result, raw_file))

    if args.dry_run:
        print("Dry run completed. No benchmark executed.")
        return

    runs_csv = output_dir / "runs_summary.csv"
    write_csv(runs_csv, run_rows)

    comparison_rows = build_short_long_comparison_rows(run_rows)
    comparison_csv = output_dir / "short_vs_long_comparison.csv"
    write_csv(comparison_csv, comparison_rows)

    markdown_file = output_dir / "short_vs_long_summary.md"
    write_short_long_markdown_summary(markdown_file, comparison_rows)

    print(f"Run summary CSV: {runs_csv.resolve()}")
    print(f"Comparison CSV: {comparison_csv.resolve()}")
    print(f"Markdown summary: {markdown_file.resolve()}")


def compare_ab_mode(args: argparse.Namespace) -> None:
    if args.baseline_dir is None or args.optimized_dir is None:
        raise ValueError(
            "--baseline-dir and --optimized-dir are required in --mode compare-ab."
        )

    baseline_csv = args.baseline_dir / "runs_summary.csv"
    optimized_csv = args.optimized_dir / "runs_summary.csv"
    baseline_rows = read_csv(baseline_csv)
    optimized_rows = read_csv(optimized_csv)

    ab_rows = build_ab_rows(
        baseline_rows=baseline_rows,
        optimized_rows=optimized_rows,
        optimized_label=args.optimized_label,
    )
    if not ab_rows:
        raise RuntimeError(
            "No matched benchmark cases between baseline and optimized runs. "
            "Please check context_group/concurrency/input_len/output_len/num_prompts."
        )

    if args.ab_output_dir is not None:
        output_dir = args.ab_output_dir
    else:
        output_dir = args.optimized_dir / f"ab_compare_vs_{args.baseline_dir.name}"
    output_dir.mkdir(parents=True, exist_ok=True)

    comparison_csv = output_dir / "ab_comparison.csv"
    summary_md = output_dir / "ab_summary.md"
    write_csv(comparison_csv, ab_rows)
    write_ab_summary_markdown(summary_md, ab_rows, args.optimized_label)

    print(f"Matched cases: {len(ab_rows)}")
    print(f"A/B comparison CSV: {comparison_csv.resolve()}")
    print(f"A/B summary markdown: {summary_md.resolve()}")


def main() -> None:
    args = parse_args()
    if args.mode == "run":
        run_mode(args)
        return
    if args.mode == "compare-ab":
        compare_ab_mode(args)
        return
    raise ValueError(f"Unsupported mode: {args.mode}")


if __name__ == "__main__":
    main()
